// All CAGRs are decimals (0.12 = 12%). expense_ratio is also decimal (0.0020 = 0.20%).
// min_risk_bucket: 'conservative' | 'moderate' | 'growth' | 'aggressive'
// priority: lower number = picked first within its asset class

export const INSTRUMENTS = [
  // ── Equity ───────────────────────────────────────────────────────────────
  {
    id: 'eq01',
    name: 'UTI Nifty 50 Index Fund Direct Growth',
    ticker: 'UTI-N50',
    asset_class: 'equity',
    sub_class: 'broad-market',
    expense_ratio: 0.0020,
    three_year_cagr: 0.125,
    five_year_cagr: 0.152,
    risk_rating: 3,
    min_risk_bucket: 'conservative',
    priority: 1,
    description: 'Passively tracks the Nifty 50 index — India\'s 50 largest companies by free-float market cap.',
    why_recommended: 'Core portfolio anchor: cheapest way to own India\'s biggest companies with near-zero tracking error.',
  },
  {
    id: 'eq02',
    name: 'UTI Nifty Next 50 Index Fund Direct Growth',
    ticker: 'UTI-NN50',
    asset_class: 'equity',
    sub_class: 'large-mid',
    expense_ratio: 0.0035,
    three_year_cagr: 0.168,
    five_year_cagr: 0.173,
    risk_rating: 4,
    min_risk_bucket: 'moderate',
    priority: 2,
    description: 'Tracks stocks ranked 51–100 by market cap — tomorrow\'s Nifty 50 candidates.',
    why_recommended: 'Historically outperformed Nifty 50 over 7+ years — adds mid-cap exposure at index fund cost.',
  },
  {
    id: 'eq03',
    name: 'Mirae Asset Large Cap Fund Direct Growth',
    ticker: 'MIRAE-LC',
    asset_class: 'equity',
    sub_class: 'large-cap',
    expense_ratio: 0.0054,
    three_year_cagr: 0.118,
    five_year_cagr: 0.146,
    risk_rating: 3,
    min_risk_bucket: 'conservative',
    priority: 3,
    description: 'Actively managed large-cap fund investing in top 100 companies by market cap.',
    why_recommended: 'Consistent large-cap performer with low portfolio churn — suitable as a stable equity anchor.',
  },
  {
    id: 'eq04',
    name: 'Parag Parikh Flexi Cap Fund Direct Growth',
    ticker: 'PPFCF',
    asset_class: 'equity',
    sub_class: 'flexi-cap',
    expense_ratio: 0.0063,
    three_year_cagr: 0.182,
    five_year_cagr: 0.214,
    risk_rating: 3,
    min_risk_bucket: 'moderate',
    priority: 2,
    description: 'Unique flexi-cap fund with up to 35% in international stocks (Alphabet, Microsoft, Amazon).',
    why_recommended: 'Adds natural USD exposure within a domestic fund — built-in global diversification with a proven long-term record.',
  },
  {
    id: 'eq05',
    name: 'Nippon India Mid Cap Fund Direct Growth',
    ticker: 'NI-MID',
    asset_class: 'equity',
    sub_class: 'mid-cap',
    expense_ratio: 0.0069,
    three_year_cagr: 0.304,
    five_year_cagr: 0.286,
    risk_rating: 4,
    min_risk_bucket: 'growth',
    priority: 2,
    description: 'Invests in mid-cap companies (101st–250th by market cap) — India\'s fast-growing tier-2 businesses.',
    why_recommended: 'Strong long-term compounder — captures growth of rising Indian businesses before they become large-caps.',
  },
  {
    id: 'eq06',
    name: 'SBI Small Cap Fund Direct Growth',
    ticker: 'SBI-SMC',
    asset_class: 'equity',
    sub_class: 'small-cap',
    expense_ratio: 0.0069,
    three_year_cagr: 0.248,
    five_year_cagr: 0.292,
    risk_rating: 5,
    min_risk_bucket: 'growth',
    priority: 3,
    description: 'Invests in small-cap companies with high growth potential — but also highest volatility.',
    why_recommended: 'Highest return potential over 7+ years — requires strong risk tolerance and patience through deep drawdowns.',
  },
  {
    id: 'eq07',
    name: 'Motilal Oswal Nasdaq 100 FoF Direct Growth',
    ticker: 'MO-N100',
    asset_class: 'equity',
    sub_class: 'international',
    expense_ratio: 0.0058,
    three_year_cagr: 0.123,
    five_year_cagr: 0.187,
    risk_rating: 4,
    min_risk_bucket: 'moderate',
    priority: 3,
    description: 'Fund of funds investing in the Nasdaq 100 ETF — tracks top 100 US non-financial tech companies.',
    why_recommended: 'US tech exposure in INR — natural hedge against INR depreciation and domestic equity concentration.',
  },
  {
    id: 'eq08',
    name: 'Axis Long Term Equity Fund (ELSS) Direct Growth',
    ticker: 'AXIS-ELSS',
    asset_class: 'equity',
    sub_class: 'elss',
    expense_ratio: 0.0057,
    three_year_cagr: 0.102,
    five_year_cagr: 0.138,
    risk_rating: 3,
    min_risk_bucket: 'conservative',
    priority: 4,
    description: 'ELSS fund with a mandatory 3-year lock-in — qualifies for ₹1.5L deduction under Section 80C.',
    why_recommended: 'Simultaneously grows wealth and saves tax — best used to maximise the ₹1.5L Section 80C limit first.',
  },
  {
    id: 'eq09',
    name: 'Nifty 500 Momentum 50 Index Fund Direct Growth',
    ticker: 'N500-MOM',
    asset_class: 'equity',
    sub_class: 'momentum',
    expense_ratio: 0.0040,
    three_year_cagr: 0.221,
    five_year_cagr: null,
    risk_rating: 4,
    min_risk_bucket: 'growth',
    priority: 3,
    description: 'Factor-based index — picks top 50 stocks from Nifty 500 ranked by price momentum.',
    why_recommended: 'Passive momentum strategy — automatically rebalances to stocks with strongest recent performance.',
  },
  {
    id: 'eq10',
    name: 'Quant Mid Cap Fund Direct Growth',
    ticker: 'QNT-MID',
    asset_class: 'equity',
    sub_class: 'mid-cap',
    expense_ratio: 0.0062,
    three_year_cagr: 0.321,
    five_year_cagr: 0.318,
    risk_rating: 5,
    min_risk_bucket: 'aggressive',
    priority: 4,
    description: 'Quantitative-model driven mid-cap fund — uses a multi-factor algorithm for stock selection.',
    why_recommended: 'Historically top-quartile returns — for aggressive investors comfortable with high active risk.',
  },
  {
    id: 'eq11',
    name: 'HDFC Flexi Cap Fund Direct Growth',
    ticker: 'HDFC-FC',
    asset_class: 'equity',
    sub_class: 'flexi-cap',
    expense_ratio: 0.0075,
    three_year_cagr: 0.164,
    five_year_cagr: 0.182,
    risk_rating: 3,
    min_risk_bucket: 'moderate',
    priority: 3,
    description: 'One of India\'s largest and oldest flexi-cap funds — multi-decade track record.',
    why_recommended: 'Trusted household name in mutual funds — suits investors who prefer time-tested fund houses.',
  },
  {
    id: 'eq12',
    name: 'Nippon India ETF Nifty Bank BeES',
    ticker: 'BANKNIFETF',
    asset_class: 'equity',
    sub_class: 'sectoral',
    expense_ratio: 0.0018,
    three_year_cagr: 0.142,
    five_year_cagr: 0.138,
    risk_rating: 4,
    min_risk_bucket: 'aggressive',
    priority: 5,
    description: 'Tracks the Nifty Bank index — concentrated bet on India\'s banking sector.',
    why_recommended: 'Cheapest route to bank sector exposure — good for tactical allocation when banking is under-owned.',
  },

  // ── Debt ─────────────────────────────────────────────────────────────────
  {
    id: 'db01',
    name: 'HDFC Liquid Fund Direct Growth',
    ticker: 'HDFC-LIQ',
    asset_class: 'debt',
    sub_class: 'liquid',
    expense_ratio: 0.0025,
    three_year_cagr: 0.065,
    five_year_cagr: 0.058,
    risk_rating: 1,
    min_risk_bucket: 'conservative',
    priority: 1,
    description: 'Invests in overnight and very short-term money market instruments. Near-zero credit and duration risk.',
    why_recommended: 'Safest debt component — capital protection with T+1 liquidity, slightly better than savings account.',
  },
  {
    id: 'db02',
    name: 'Kotak Corporate Bond Fund Direct Growth',
    ticker: 'KOT-CB',
    asset_class: 'debt',
    sub_class: 'corporate-bond',
    expense_ratio: 0.0035,
    three_year_cagr: 0.072,
    five_year_cagr: 0.075,
    risk_rating: 2,
    min_risk_bucket: 'conservative',
    priority: 2,
    description: 'Invests primarily in AAA-rated corporate bonds with 1–3 year maturity.',
    why_recommended: 'Higher yield than liquid funds with low credit risk — ideal for 1+ year debt allocation.',
  },
  {
    id: 'db03',
    name: 'Axis Short Duration Fund Direct Growth',
    ticker: 'AXIS-SD',
    asset_class: 'debt',
    sub_class: 'short-duration',
    expense_ratio: 0.0035,
    three_year_cagr: 0.068,
    five_year_cagr: 0.071,
    risk_rating: 2,
    min_risk_bucket: 'conservative',
    priority: 2,
    description: 'Maintains a portfolio duration of 1–3 years — balances yield with moderate interest rate risk.',
    why_recommended: 'Sweet spot between liquid funds and medium-duration debt — good core fixed-income holding.',
  },
  {
    id: 'db04',
    name: 'Edelweiss BHARAT Bond ETF Apr 2034',
    ticker: 'BHART-B',
    asset_class: 'debt',
    sub_class: 'psu-bond',
    expense_ratio: 0.0008,
    three_year_cagr: 0.078,
    five_year_cagr: 0.080,
    risk_rating: 1,
    min_risk_bucket: 'conservative',
    priority: 2,
    description: 'Target-maturity ETF investing in AAA PSU bonds maturing in April 2034. Lowest expense ratio in debt.',
    why_recommended: 'Sovereign-quality PSU bonds with roll-down certainty — near-zero credit risk at 0.08% expense ratio.',
  },
  {
    id: 'db05',
    name: 'PPF (Public Provident Fund)',
    ticker: 'PPF',
    asset_class: 'debt',
    sub_class: 'government',
    expense_ratio: 0,
    three_year_cagr: 0.071,
    five_year_cagr: 0.071,
    risk_rating: 1,
    min_risk_bucket: 'conservative',
    priority: 3,
    description: 'Government-backed 15-year savings scheme. Zero credit risk, tax-free returns under EEE regime.',
    why_recommended: 'Best risk-adjusted return in debt — triple tax exempt (invest, accumulate, withdraw). Max ₹1.5L/year.',
  },
  {
    id: 'db06',
    name: 'SBI Magnum Gilt Fund Direct Growth',
    ticker: 'SBI-GILT',
    asset_class: 'debt',
    sub_class: 'gilt',
    expense_ratio: 0.0046,
    three_year_cagr: 0.084,
    five_year_cagr: 0.082,
    risk_rating: 2,
    min_risk_bucket: 'conservative',
    priority: 3,
    description: 'Invests exclusively in government securities — zero credit risk, but interest rate sensitive.',
    why_recommended: 'Highest quality debt: pure sovereign exposure. Gains when RBI cuts rates.',
  },
  {
    id: 'db07',
    name: 'ICICI Pru All Seasons Bond Fund Direct Growth',
    ticker: 'IPRU-ASB',
    asset_class: 'debt',
    sub_class: 'dynamic-bond',
    expense_ratio: 0.0068,
    three_year_cagr: 0.079,
    five_year_cagr: 0.081,
    risk_rating: 2,
    min_risk_bucket: 'moderate',
    priority: 3,
    description: 'Dynamic duration fund — fund manager actively shifts duration 1–10 years based on rate outlook.',
    why_recommended: 'Active interest rate play — captures rate-cut gains while limiting losses in rising-rate environments.',
  },
  {
    id: 'db08',
    name: 'SBI Banking & PSU Debt Fund Direct Growth',
    ticker: 'SBI-BPSU',
    asset_class: 'debt',
    sub_class: 'banking-psu',
    expense_ratio: 0.0042,
    three_year_cagr: 0.074,
    five_year_cagr: 0.076,
    risk_rating: 1,
    min_risk_bucket: 'conservative',
    priority: 4,
    description: 'Invests in bonds issued by banks and PSUs — very high credit quality at better yields.',
    why_recommended: 'Between liquid and corporate bond in risk/return — steady, predictable debt component.',
  },
  {
    id: 'db09',
    name: 'HDFC Floating Rate Debt Fund Direct Growth',
    ticker: 'HDFC-FRD',
    asset_class: 'debt',
    sub_class: 'floating-rate',
    expense_ratio: 0.0038,
    three_year_cagr: 0.071,
    five_year_cagr: 0.073,
    risk_rating: 2,
    min_risk_bucket: 'conservative',
    priority: 4,
    description: 'Invests in floating-rate bonds whose coupon resets with market rates — minimal duration risk.',
    why_recommended: 'Natural rate-rise hedge — returns improve when RBI raises rates, protecting capital value.',
  },

  // ── Gold ─────────────────────────────────────────────────────────────────
  {
    id: 'gd01',
    name: 'Nippon India Gold ETF',
    ticker: 'NI-GOLD',
    asset_class: 'gold',
    sub_class: 'gold-etf',
    expense_ratio: 0.0044,
    three_year_cagr: 0.132,
    five_year_cagr: 0.128,
    risk_rating: 2,
    min_risk_bucket: 'conservative',
    priority: 1,
    description: 'Physical gold ETF — each unit represents approximately 1 gram of 99.5% pure gold.',
    why_recommended: 'Best SIP-friendly gold option: real-time pricing, demat convenience, no storage risk.',
  },
  {
    id: 'gd02',
    name: 'Axis Gold Fund Direct Growth',
    ticker: 'AXIS-GOLD',
    asset_class: 'gold',
    sub_class: 'gold-fof',
    expense_ratio: 0.0055,
    three_year_cagr: 0.128,
    five_year_cagr: 0.124,
    risk_rating: 2,
    min_risk_bucket: 'conservative',
    priority: 2,
    description: 'Fund of funds that invests in Axis Gold ETF — accessible without a demat account.',
    why_recommended: 'Invest in gold via SIP without a demat account — ideal for mutual fund-only investors.',
  },
  {
    id: 'gd03',
    name: 'HDFC Gold ETF',
    ticker: 'HDFC-GOLD',
    asset_class: 'gold',
    sub_class: 'gold-etf',
    expense_ratio: 0.0042,
    three_year_cagr: 0.130,
    five_year_cagr: 0.126,
    risk_rating: 2,
    min_risk_bucket: 'conservative',
    priority: 3,
    description: 'Physical gold ETF from HDFC AMC — one of the most liquid gold ETFs on NSE.',
    why_recommended: 'Low-cost alternative to Nippon Gold ETF — ideal for those already using HDFC AMC for equity funds.',
  },
  {
    id: 'gd04',
    name: 'Sovereign Gold Bond (SGB)',
    ticker: 'SGB',
    asset_class: 'gold',
    sub_class: 'gold-bond',
    expense_ratio: 0,
    three_year_cagr: 0.141,
    five_year_cagr: 0.135,
    risk_rating: 2,
    min_risk_bucket: 'conservative',
    priority: 4,
    description: 'Government of India bond linked to gold price — pays 2.5% annual interest on top of price gain.',
    why_recommended: 'Best absolute return on gold: 2.5% guaranteed interest + gold price appreciation + tax-free on maturity.',
  },

  // ── Alternatives (REITs / commodities / InvITs — Growth+ only) ────────────
  {
    id: 'al01',
    name: 'Embassy Office Parks REIT',
    ticker: 'EMBASSY-R',
    asset_class: 'alternatives',
    sub_class: 'reit',
    expense_ratio: 0.0100,
    three_year_cagr: 0.068,
    five_year_cagr: 0.072,
    risk_rating: 3,
    min_risk_bucket: 'growth',
    priority: 1,
    description: 'India\'s largest REIT — 45M+ sq ft of Grade-A office space leased to multinational companies.',
    why_recommended: 'Real estate exposure without buying property: quarterly distributions + price appreciation from premium office parks.',
  },
  {
    id: 'al02',
    name: 'Mindspace Business Parks REIT',
    ticker: 'MSPACE-R',
    asset_class: 'alternatives',
    sub_class: 'reit',
    expense_ratio: 0.0090,
    three_year_cagr: 0.071,
    five_year_cagr: 0.080,
    risk_rating: 3,
    min_risk_bucket: 'growth',
    priority: 2,
    description: 'Blackstone-backed commercial REIT with 32M sq ft across Mumbai, Hyderabad, Chennai, Pune.',
    why_recommended: 'Stable distributions from blue-chip tech tenants — good diversifier for a growth-oriented portfolio.',
  },
  {
    id: 'al03',
    name: 'Nippon India Commodities Fund Direct Growth',
    ticker: 'NI-COMM',
    asset_class: 'alternatives',
    sub_class: 'commodities',
    expense_ratio: 0.0120,
    three_year_cagr: 0.084,
    five_year_cagr: 0.078,
    risk_rating: 3,
    min_risk_bucket: 'growth',
    priority: 3,
    description: 'Diversified commodity fund — exposure to energy, metals, and agricultural commodities.',
    why_recommended: 'Inflation hedge beyond gold — commodity prices often rise when equities fall.',
  },
  {
    id: 'al04',
    name: 'Mirae Asset S&P 500 Top 50 ETF FoF Direct Growth',
    ticker: 'MIRAE-SP',
    asset_class: 'alternatives',
    sub_class: 'international-equity',
    expense_ratio: 0.0045,
    three_year_cagr: 0.162,
    five_year_cagr: 0.178,
    risk_rating: 4,
    min_risk_bucket: 'aggressive',
    priority: 2,
    description: 'FoF tracking the top 50 US megacap stocks — Apple, Microsoft, Nvidia, Amazon, Meta, Alphabet.',
    why_recommended: 'Concentrated US megacap exposure — benefits from USD appreciation and dominant global tech businesses.',
  },
  {
    id: 'al05',
    name: 'IndInfravit Trust',
    ticker: 'INDINVIT',
    asset_class: 'alternatives',
    sub_class: 'infra-invit',
    expense_ratio: 0.0150,
    three_year_cagr: 0.059,
    five_year_cagr: null,
    risk_rating: 3,
    min_risk_bucket: 'growth',
    priority: 4,
    description: 'Infrastructure investment trust holding toll-road assets — predictable toll revenue from highways.',
    why_recommended: 'Stable, inflation-linked distributions from highway toll revenue — uncorrelated to equity markets.',
  },
]

export const CASH_INSTRUMENT = {
  id: 'cash01',
  name: 'High-Yield Savings / Liquid Fund',
  ticker: 'LIQUID',
  asset_class: 'cash',
  sub_class: 'savings',
  expense_ratio: 0.0020,
  three_year_cagr: 0.065,
  five_year_cagr: 0.060,
  risk_rating: 1,
  min_risk_bucket: 'conservative',
  priority: 1,
  description: 'Park short-term cash in a liquid fund (HDFC/ICICI/SBI) or a high-yield digital savings account.',
  why_recommended: 'Capital safety with T+1 liquidity — better than letting cash sit idle in a regular savings account.',
}
