// All CAGRs are decimals (0.12 = 12%). expense_ratio is also decimal (0.0020 = 0.20%).
// min_risk_bucket: 'conservative' | 'moderate' | 'growth' | 'aggressive'
// priority: lower number = picked first within its asset class

export const INSTRUMENTS = [

  // ══════════════════════════════════════════════════════════════════
  // EQUITY — Index Funds (Passive)
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'eq01',
    name: 'UTI Nifty 50 Index Fund Direct Growth',
    ticker: 'UTI-N50',
    asset_class: 'equity', sub_class: 'broad-market',
    expense_ratio: 0.0020, three_year_cagr: 0.125, five_year_cagr: 0.152,
    risk_rating: 3, min_risk_bucket: 'conservative', priority: 1,
    description: 'Passively tracks the Nifty 50 index — India\'s 50 largest companies by free-float market cap.',
    why_recommended: 'Core portfolio anchor: cheapest way to own India\'s biggest companies with near-zero tracking error.',
  },
  {
    id: 'eq02',
    name: 'UTI Nifty Next 50 Index Fund Direct Growth',
    ticker: 'UTI-NN50',
    asset_class: 'equity', sub_class: 'large-mid',
    expense_ratio: 0.0035, three_year_cagr: 0.168, five_year_cagr: 0.173,
    risk_rating: 4, min_risk_bucket: 'moderate', priority: 2,
    description: 'Tracks stocks ranked 51–100 by market cap — tomorrow\'s Nifty 50 candidates.',
    why_recommended: 'Historically outperformed Nifty 50 over 7+ years — adds mid-cap exposure at index fund cost.',
  },
  {
    id: 'eq09',
    name: 'Nifty 500 Momentum 50 Index Fund Direct Growth',
    ticker: 'N500-MOM',
    asset_class: 'equity', sub_class: 'factor',
    expense_ratio: 0.0040, three_year_cagr: 0.221, five_year_cagr: null,
    risk_rating: 4, min_risk_bucket: 'growth', priority: 3,
    description: 'Factor-based index — picks top 50 stocks from Nifty 500 ranked by price momentum.',
    why_recommended: 'Passive momentum strategy — automatically rebalances to stocks with strongest recent performance.',
  },
  {
    id: 'eq17',
    name: 'Nifty Alpha 50 Index Fund Direct Growth',
    ticker: 'N-ALPHA50',
    asset_class: 'equity', sub_class: 'factor',
    expense_ratio: 0.0035, three_year_cagr: 0.235, five_year_cagr: null,
    risk_rating: 4, min_risk_bucket: 'growth', priority: 4,
    description: 'Tracks the top 50 high-alpha stocks from Nifty 500 — selects companies that consistently outperform the market.',
    why_recommended: 'Smart-beta strategy capturing market outperformers at passive fund cost — strong bull market performer.',
  },
  {
    id: 'eq18',
    name: 'Nifty Low Volatility 50 Index Fund Direct Growth',
    ticker: 'N-LVOL50',
    asset_class: 'equity', sub_class: 'factor',
    expense_ratio: 0.0030, three_year_cagr: 0.148, five_year_cagr: 0.162,
    risk_rating: 3, min_risk_bucket: 'moderate', priority: 3,
    description: 'Selects 50 least-volatile stocks from Nifty 100 — defensive equity positioning.',
    why_recommended: 'Smoother ride than broad market — better downside protection for conservative equity investors.',
  },
  {
    id: 'eq19',
    name: 'DSP Nifty 50 Equal Weight Index Fund Direct Growth',
    ticker: 'DSP-EW50',
    asset_class: 'equity', sub_class: 'broad-market',
    expense_ratio: 0.0040, three_year_cagr: 0.138, five_year_cagr: 0.155,
    risk_rating: 3, min_risk_bucket: 'moderate', priority: 4,
    description: 'Equal weight version of Nifty 50 — each of 50 stocks gets 2% weight, reducing mega-cap concentration.',
    why_recommended: 'Avoids over-concentration in Reliance/TCS/HDFC — better mid-tier large-cap exposure within Nifty 50.',
  },
  {
    id: 'eq26',
    name: 'Nifty Midcap 150 Index Fund Direct Growth',
    ticker: 'N-MID150',
    asset_class: 'equity', sub_class: 'mid-cap',
    expense_ratio: 0.0035, three_year_cagr: 0.268, five_year_cagr: 0.272,
    risk_rating: 4, min_risk_bucket: 'growth', priority: 3,
    description: 'Passively tracks all 150 mid-cap stocks — broadest mid-cap index fund available.',
    why_recommended: 'Widest mid-cap diversification at index fund cost — eliminates fund manager selection risk in mid-caps.',
  },
  {
    id: 'eq27',
    name: 'Nifty Smallcap 250 Index Fund Direct Growth',
    ticker: 'N-SMC250',
    asset_class: 'equity', sub_class: 'small-cap',
    expense_ratio: 0.0045, three_year_cagr: 0.252, five_year_cagr: 0.258,
    risk_rating: 5, min_risk_bucket: 'aggressive', priority: 3,
    description: 'Passively tracks 250 small-cap companies — most diversified small-cap index fund.',
    why_recommended: 'Cheapest way to own the entire small-cap universe — removes single-stock risk across 250 companies.',
  },

  // ══════════════════════════════════════════════════════════════════
  // EQUITY — Active Large Cap
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'eq03',
    name: 'Mirae Asset Large Cap Fund Direct Growth',
    ticker: 'MIRAE-LC',
    asset_class: 'equity', sub_class: 'large-cap',
    expense_ratio: 0.0054, three_year_cagr: 0.118, five_year_cagr: 0.146,
    risk_rating: 3, min_risk_bucket: 'conservative', priority: 3,
    description: 'Actively managed large-cap fund investing in top 100 companies by market cap.',
    why_recommended: 'Consistent large-cap performer with low portfolio churn — suitable as a stable equity anchor.',
  },
  {
    id: 'eq13',
    name: 'ICICI Pru Bluechip Fund Direct Growth',
    ticker: 'IPRU-BC',
    asset_class: 'equity', sub_class: 'large-cap',
    expense_ratio: 0.0087, three_year_cagr: 0.163, five_year_cagr: 0.178,
    risk_rating: 3, min_risk_bucket: 'conservative', priority: 4,
    description: 'One of India\'s largest large-cap funds — diversified portfolio of top 30–40 blue-chip stocks.',
    why_recommended: 'Decade-long consistent performer with strong downside protection during corrections.',
  },
  {
    id: 'eq28',
    name: 'HDFC Top 100 Fund Direct Growth',
    ticker: 'HDFC-T100',
    asset_class: 'equity', sub_class: 'large-cap',
    expense_ratio: 0.0095, three_year_cagr: 0.172, five_year_cagr: 0.181,
    risk_rating: 3, min_risk_bucket: 'conservative', priority: 5,
    description: 'Invests in top 100 companies by market cap — one of India\'s oldest actively managed large-cap funds.',
    why_recommended: 'Strong track record through multiple market cycles — fund manager Prashant Jain legacy fund.',
  },

  // ══════════════════════════════════════════════════════════════════
  // EQUITY — Active Flexi / Multi Cap
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'eq04',
    name: 'Parag Parikh Flexi Cap Fund Direct Growth',
    ticker: 'PPFCF',
    asset_class: 'equity', sub_class: 'flexi-cap',
    expense_ratio: 0.0063, three_year_cagr: 0.182, five_year_cagr: 0.214,
    risk_rating: 3, min_risk_bucket: 'moderate', priority: 2,
    description: 'Unique flexi-cap fund with up to 35% in international stocks (Alphabet, Microsoft, Amazon).',
    why_recommended: 'Adds natural USD exposure within a domestic fund — built-in global diversification with a proven long-term record.',
  },
  {
    id: 'eq11',
    name: 'HDFC Flexi Cap Fund Direct Growth',
    ticker: 'HDFC-FC',
    asset_class: 'equity', sub_class: 'flexi-cap',
    expense_ratio: 0.0075, three_year_cagr: 0.164, five_year_cagr: 0.182,
    risk_rating: 3, min_risk_bucket: 'moderate', priority: 3,
    description: 'One of India\'s largest and oldest flexi-cap funds — multi-decade track record.',
    why_recommended: 'Trusted household name in mutual funds — suits investors who prefer time-tested fund houses.',
  },
  {
    id: 'eq22',
    name: 'ICICI Pru Value Discovery Fund Direct Growth',
    ticker: 'IPRU-VD',
    asset_class: 'equity', sub_class: 'value',
    expense_ratio: 0.0099, three_year_cagr: 0.195, five_year_cagr: 0.218,
    risk_rating: 3, min_risk_bucket: 'moderate', priority: 3,
    description: 'Contrarian value fund — buys quality businesses trading below intrinsic value.',
    why_recommended: 'Outperforms in market recoveries — disciplined value approach with 20+ year track record.',
  },
  {
    id: 'eq29',
    name: 'Canara Robeco Emerging Equities Fund Direct Growth',
    ticker: 'CR-EMRG',
    asset_class: 'equity', sub_class: 'large-mid',
    expense_ratio: 0.0058, three_year_cagr: 0.192, five_year_cagr: 0.207,
    risk_rating: 4, min_risk_bucket: 'moderate', priority: 4,
    description: 'Large and mid-cap fund with consistent top-quartile performance — low churn, quality-focused.',
    why_recommended: 'Rare combination of low expense ratio and strong alpha generation — underrated by most investors.',
  },

  // ══════════════════════════════════════════════════════════════════
  // EQUITY — Active Mid Cap
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'eq05',
    name: 'Nippon India Mid Cap Fund Direct Growth',
    ticker: 'NI-MID',
    asset_class: 'equity', sub_class: 'mid-cap',
    expense_ratio: 0.0069, three_year_cagr: 0.304, five_year_cagr: 0.286,
    risk_rating: 4, min_risk_bucket: 'growth', priority: 2,
    description: 'Invests in mid-cap companies (101st–250th by market cap) — India\'s fast-growing tier-2 businesses.',
    why_recommended: 'Strong long-term compounder — captures growth of rising Indian businesses before they become large-caps.',
  },
  {
    id: 'eq23',
    name: 'Kotak Emerging Equity Fund Direct Growth',
    ticker: 'KOT-EMRG',
    asset_class: 'equity', sub_class: 'mid-cap',
    expense_ratio: 0.0047, three_year_cagr: 0.282, five_year_cagr: 0.265,
    risk_rating: 4, min_risk_bucket: 'growth', priority: 3,
    description: 'Mid-cap fund with quality focus — lower turnover than peers, holds businesses for years.',
    why_recommended: 'Lowest churn among mid-cap peers — ideal for patient investors who want mid-cap exposure without hyper-active trading.',
  },
  {
    id: 'eq30',
    name: 'Franklin India Prima Fund Direct Growth',
    ticker: 'FI-PRIMA',
    asset_class: 'equity', sub_class: 'mid-cap',
    expense_ratio: 0.0087, three_year_cagr: 0.274, five_year_cagr: 0.258,
    risk_rating: 4, min_risk_bucket: 'growth', priority: 4,
    description: 'One of India\'s oldest mid-cap funds with a focus on emerging business leaders.',
    why_recommended: 'Battle-tested through multiple cycles — identifies mid-cap companies before they hit mainstream radar.',
  },
  {
    id: 'eq10',
    name: 'Quant Mid Cap Fund Direct Growth',
    ticker: 'QNT-MID',
    asset_class: 'equity', sub_class: 'mid-cap',
    expense_ratio: 0.0062, three_year_cagr: 0.321, five_year_cagr: 0.318,
    risk_rating: 5, min_risk_bucket: 'aggressive', priority: 5,
    description: 'Quantitative-model driven mid-cap fund — uses a multi-factor algorithm for stock selection.',
    why_recommended: 'Historically top-quartile returns — for aggressive investors comfortable with high active risk.',
  },

  // ══════════════════════════════════════════════════════════════════
  // EQUITY — Active Small Cap
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'eq06',
    name: 'SBI Small Cap Fund Direct Growth',
    ticker: 'SBI-SMC',
    asset_class: 'equity', sub_class: 'small-cap',
    expense_ratio: 0.0069, three_year_cagr: 0.248, five_year_cagr: 0.292,
    risk_rating: 5, min_risk_bucket: 'growth', priority: 3,
    description: 'Invests in small-cap companies with high growth potential — but also highest volatility.',
    why_recommended: 'Highest return potential over 7+ years — requires strong risk tolerance and patience through deep drawdowns.',
  },
  {
    id: 'eq14',
    name: 'DSP Small Cap Fund Direct Growth',
    ticker: 'DSP-SMC',
    asset_class: 'equity', sub_class: 'small-cap',
    expense_ratio: 0.0073, three_year_cagr: 0.261, five_year_cagr: 0.298,
    risk_rating: 5, min_risk_bucket: 'growth', priority: 4,
    description: 'Quality-focused small cap fund — avoids low-quality companies, targets undiscovered compounders.',
    why_recommended: 'Consistent peer-topper with disciplined quality screen — better drawdown management than most small-cap peers.',
  },

  // ══════════════════════════════════════════════════════════════════
  // EQUITY — Sectoral & Thematic
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'eq12',
    name: 'Nippon India ETF Nifty Bank BeES',
    ticker: 'BANKNIFETF',
    asset_class: 'equity', sub_class: 'sectoral-banking',
    expense_ratio: 0.0018, three_year_cagr: 0.142, five_year_cagr: 0.138,
    risk_rating: 4, min_risk_bucket: 'aggressive', priority: 5,
    description: 'Tracks the Nifty Bank index — concentrated bet on India\'s banking sector.',
    why_recommended: 'Cheapest route to bank sector exposure — good for tactical allocation when banking is under-owned.',
  },
  {
    id: 'eq15',
    name: 'Tata Digital India Fund Direct Growth',
    ticker: 'TATA-DIG',
    asset_class: 'equity', sub_class: 'sectoral-technology',
    expense_ratio: 0.0029, three_year_cagr: 0.108, five_year_cagr: 0.242,
    risk_rating: 5, min_risk_bucket: 'aggressive', priority: 4,
    description: 'Pure-play technology sector fund — IT services, software, internet, and digital businesses.',
    why_recommended: 'Best way to bet on India\'s IT sector boom — TCS, Infosys, HCL, Wipro plus digital-native companies.',
  },
  {
    id: 'eq24',
    name: 'Nippon India ETF Nifty IT',
    ticker: 'NI-IT-ETF',
    asset_class: 'equity', sub_class: 'sectoral-technology',
    expense_ratio: 0.0020, three_year_cagr: 0.104, five_year_cagr: 0.238,
    risk_rating: 5, min_risk_bucket: 'aggressive', priority: 5,
    description: 'Exchange-traded fund tracking Nifty IT index — real-time trading on NSE.',
    why_recommended: 'Lowest cost IT sector exposure traded like a stock — ideal for tactical technology overweights.',
  },
  {
    id: 'eq16',
    name: 'HDFC Defence Fund Direct Growth',
    ticker: 'HDFC-DEF',
    asset_class: 'equity', sub_class: 'sectoral-defence',
    expense_ratio: 0.0070, three_year_cagr: 0.412, five_year_cagr: null,
    risk_rating: 5, min_risk_bucket: 'aggressive', priority: 5,
    description: 'New-age thematic fund investing in India\'s defence and aerospace sector companies.',
    why_recommended: 'Captures India\'s defence indigenisation wave — HAL, BEL, Bharat Forge, DRDO-linked companies.',
  },
  {
    id: 'eq31',
    name: 'Nippon India Pharma Fund Direct Growth',
    ticker: 'NI-PHARM',
    asset_class: 'equity', sub_class: 'sectoral-pharma',
    expense_ratio: 0.0075, three_year_cagr: 0.162, five_year_cagr: 0.198,
    risk_rating: 4, min_risk_bucket: 'aggressive', priority: 5,
    description: 'Pharma and healthcare sector fund — India\'s generic drug exporters, hospitals, diagnostic chains.',
    why_recommended: 'Defensive sector with strong export earnings — acts as counter-cyclical hedge to financial and manufacturing exposure.',
  },
  {
    id: 'eq25',
    name: 'Nifty India Consumption Index Fund Direct Growth',
    ticker: 'N-CONSMP',
    asset_class: 'equity', sub_class: 'sectoral-consumption',
    expense_ratio: 0.0040, three_year_cagr: 0.138, five_year_cagr: 0.162,
    risk_rating: 3, min_risk_bucket: 'moderate', priority: 4,
    description: 'Tracks consumer discretionary and FMCG companies — Hindustan Unilever, ITC, Titan, Maruti.',
    why_recommended: 'Ride India\'s consumption story — growing middle class spending on branded goods, vehicles, and experiences.',
  },

  // ══════════════════════════════════════════════════════════════════
  // EQUITY — ELSS & International
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'eq08',
    name: 'Axis Long Term Equity Fund (ELSS) Direct Growth',
    ticker: 'AXIS-ELSS',
    asset_class: 'equity', sub_class: 'elss',
    expense_ratio: 0.0057, three_year_cagr: 0.102, five_year_cagr: 0.138,
    risk_rating: 3, min_risk_bucket: 'conservative', priority: 4,
    description: 'ELSS fund with a mandatory 3-year lock-in — qualifies for ₹1.5L deduction under Section 80C.',
    why_recommended: 'Simultaneously grows wealth and saves tax — best used to maximise the ₹1.5L Section 80C limit first.',
  },
  {
    id: 'eq32',
    name: 'Mirae Asset Tax Saver Fund (ELSS) Direct Growth',
    ticker: 'MIRAE-ELSS',
    asset_class: 'equity', sub_class: 'elss',
    expense_ratio: 0.0051, three_year_cagr: 0.158, five_year_cagr: 0.184,
    risk_rating: 3, min_risk_bucket: 'conservative', priority: 5,
    description: 'ELSS with large-cap focus — tax saving with lower volatility than mid-cap ELSS alternatives.',
    why_recommended: 'Best ELSS for conservative investors — Section 80C benefit with blue-chip equity stability.',
  },
  {
    id: 'eq07',
    name: 'Motilal Oswal Nasdaq 100 FoF Direct Growth',
    ticker: 'MO-N100',
    asset_class: 'equity', sub_class: 'international',
    expense_ratio: 0.0058, three_year_cagr: 0.123, five_year_cagr: 0.187,
    risk_rating: 4, min_risk_bucket: 'moderate', priority: 3,
    description: 'Fund of funds investing in the Nasdaq 100 ETF — tracks top 100 US non-financial tech companies.',
    why_recommended: 'US tech exposure in INR — natural hedge against INR depreciation and domestic equity concentration.',
  },

  // ══════════════════════════════════════════════════════════════════
  // DEBT — Overnight & Liquid
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'db10',
    name: 'Nippon India Overnight Fund Direct Growth',
    ticker: 'NI-OVNT',
    asset_class: 'debt', sub_class: 'overnight',
    expense_ratio: 0.0010, three_year_cagr: 0.064, five_year_cagr: 0.056,
    risk_rating: 1, min_risk_bucket: 'conservative', priority: 1,
    description: 'Invests only in overnight instruments — no interest rate or credit risk whatsoever.',
    why_recommended: 'Absolute safest parking: next-day liquidity with near-zero NAV volatility — better than savings account.',
  },
  {
    id: 'db01',
    name: 'HDFC Liquid Fund Direct Growth',
    ticker: 'HDFC-LIQ',
    asset_class: 'debt', sub_class: 'liquid',
    expense_ratio: 0.0025, three_year_cagr: 0.065, five_year_cagr: 0.058,
    risk_rating: 1, min_risk_bucket: 'conservative', priority: 2,
    description: 'Invests in overnight and very short-term money market instruments. Near-zero credit and duration risk.',
    why_recommended: 'Safest debt component — capital protection with T+1 liquidity, slightly better than savings account.',
  },

  // ══════════════════════════════════════════════════════════════════
  // DEBT — Ultra Short & Low Duration
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'db17',
    name: 'HDFC Ultra Short Term Fund Direct Growth',
    ticker: 'HDFC-UST',
    asset_class: 'debt', sub_class: 'ultra-short',
    expense_ratio: 0.0030, three_year_cagr: 0.066, five_year_cagr: 0.065,
    risk_rating: 1, min_risk_bucket: 'conservative', priority: 2,
    description: 'Invests in instruments maturing in 3–6 months — marginally better yield than liquid funds.',
    why_recommended: 'Perfect 3–6 month parking spot — beats liquid fund return without materially adding risk.',
  },
  {
    id: 'db11',
    name: 'ICICI Pru Savings Fund Direct Growth',
    ticker: 'IPRU-SAV',
    asset_class: 'debt', sub_class: 'low-duration',
    expense_ratio: 0.0040, three_year_cagr: 0.069, five_year_cagr: 0.070,
    risk_rating: 2, min_risk_bucket: 'conservative', priority: 3,
    description: 'Low-duration fund with 6–12 month maturity profile — higher yield than ultra-short with minimal risk.',
    why_recommended: 'Step up from liquid funds for 6–12 month horizon — better yield with manageable interest rate sensitivity.',
  },

  // ══════════════════════════════════════════════════════════════════
  // DEBT — Short & Medium Duration
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'db03',
    name: 'Axis Short Duration Fund Direct Growth',
    ticker: 'AXIS-SD',
    asset_class: 'debt', sub_class: 'short-duration',
    expense_ratio: 0.0035, three_year_cagr: 0.068, five_year_cagr: 0.071,
    risk_rating: 2, min_risk_bucket: 'conservative', priority: 2,
    description: 'Maintains a portfolio duration of 1–3 years — balances yield with moderate interest rate risk.',
    why_recommended: 'Sweet spot between liquid funds and medium-duration debt — good core fixed-income holding.',
  },
  {
    id: 'db18',
    name: 'ICICI Pru Medium Term Bond Fund Direct Growth',
    ticker: 'IPRU-MTB',
    asset_class: 'debt', sub_class: 'medium-duration',
    expense_ratio: 0.0078, three_year_cagr: 0.076, five_year_cagr: 0.079,
    risk_rating: 2, min_risk_bucket: 'moderate', priority: 3,
    description: '3–4 year duration corporate bond fund — meaningful yield pickup over short-duration peers.',
    why_recommended: 'Bridge between short and long duration — appropriate for 3–5 year investment horizon.',
  },
  {
    id: 'db07',
    name: 'ICICI Pru All Seasons Bond Fund Direct Growth',
    ticker: 'IPRU-ASB',
    asset_class: 'debt', sub_class: 'dynamic-bond',
    expense_ratio: 0.0068, three_year_cagr: 0.079, five_year_cagr: 0.081,
    risk_rating: 2, min_risk_bucket: 'moderate', priority: 3,
    description: 'Dynamic duration fund — fund manager actively shifts duration 1–10 years based on rate outlook.',
    why_recommended: 'Active interest rate play — captures rate-cut gains while limiting losses in rising-rate environments.',
  },

  // ══════════════════════════════════════════════════════════════════
  // DEBT — Corporate & Banking PSU Bonds
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'db02',
    name: 'Kotak Corporate Bond Fund Direct Growth',
    ticker: 'KOT-CB',
    asset_class: 'debt', sub_class: 'corporate-bond',
    expense_ratio: 0.0035, three_year_cagr: 0.072, five_year_cagr: 0.075,
    risk_rating: 2, min_risk_bucket: 'conservative', priority: 2,
    description: 'Invests primarily in AAA-rated corporate bonds with 1–3 year maturity.',
    why_recommended: 'Higher yield than liquid funds with low credit risk — ideal for 1+ year debt allocation.',
  },
  {
    id: 'db08',
    name: 'SBI Banking & PSU Debt Fund Direct Growth',
    ticker: 'SBI-BPSU',
    asset_class: 'debt', sub_class: 'banking-psu',
    expense_ratio: 0.0042, three_year_cagr: 0.074, five_year_cagr: 0.076,
    risk_rating: 1, min_risk_bucket: 'conservative', priority: 4,
    description: 'Invests in bonds issued by banks and PSUs — very high credit quality at better yields.',
    why_recommended: 'Between liquid and corporate bond in risk/return — steady, predictable debt component.',
  },
  {
    id: 'db09',
    name: 'HDFC Floating Rate Debt Fund Direct Growth',
    ticker: 'HDFC-FRD',
    asset_class: 'debt', sub_class: 'floating-rate',
    expense_ratio: 0.0038, three_year_cagr: 0.071, five_year_cagr: 0.073,
    risk_rating: 2, min_risk_bucket: 'conservative', priority: 4,
    description: 'Invests in floating-rate bonds whose coupon resets with market rates — minimal duration risk.',
    why_recommended: 'Natural rate-rise hedge — returns improve when RBI raises rates, protecting capital value.',
  },

  // ══════════════════════════════════════════════════════════════════
  // DEBT — Gilt & Target Maturity ETFs
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'db06',
    name: 'SBI Magnum Gilt Fund Direct Growth',
    ticker: 'SBI-GILT',
    asset_class: 'debt', sub_class: 'gilt',
    expense_ratio: 0.0046, three_year_cagr: 0.084, five_year_cagr: 0.082,
    risk_rating: 2, min_risk_bucket: 'conservative', priority: 3,
    description: 'Invests exclusively in government securities — zero credit risk, but interest rate sensitive.',
    why_recommended: 'Highest quality debt: pure sovereign exposure. Gains when RBI cuts rates.',
  },
  {
    id: 'db04',
    name: 'Edelweiss BHARAT Bond ETF Apr 2034',
    ticker: 'BHART-B34',
    asset_class: 'debt', sub_class: 'target-maturity',
    expense_ratio: 0.0008, three_year_cagr: 0.078, five_year_cagr: 0.080,
    risk_rating: 1, min_risk_bucket: 'conservative', priority: 2,
    description: 'Target-maturity ETF investing in AAA PSU bonds maturing in April 2034. Lowest expense ratio in debt.',
    why_recommended: 'Sovereign-quality PSU bonds with roll-down certainty — near-zero credit risk at 0.08% expense ratio.',
  },
  {
    id: 'db19',
    name: 'Edelweiss BHARAT Bond ETF Apr 2031',
    ticker: 'BHART-B31',
    asset_class: 'debt', sub_class: 'target-maturity',
    expense_ratio: 0.0008, three_year_cagr: 0.076, five_year_cagr: 0.079,
    risk_rating: 1, min_risk_bucket: 'conservative', priority: 3,
    description: 'Shorter-dated target maturity PSU bond ETF — known yield to maturity with 2031 roll-off.',
    why_recommended: 'Predictable debt instrument for 7-year goal matching — you know your return before you invest.',
  },

  // ══════════════════════════════════════════════════════════════════
  // DEBT — Government Savings Schemes
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'db05',
    name: 'PPF (Public Provident Fund)',
    ticker: 'PPF',
    asset_class: 'debt', sub_class: 'government-scheme',
    expense_ratio: 0, three_year_cagr: 0.071, five_year_cagr: 0.071,
    risk_rating: 1, min_risk_bucket: 'conservative', priority: 3,
    description: 'Government-backed 15-year savings scheme. Zero credit risk, tax-free returns under EEE regime.',
    why_recommended: 'Best risk-adjusted return in debt — triple tax exempt (invest, accumulate, withdraw). Max ₹1.5L/year.',
  },
  {
    id: 'db20',
    name: 'NSC (National Savings Certificate)',
    ticker: 'NSC',
    asset_class: 'debt', sub_class: 'government-scheme',
    expense_ratio: 0, three_year_cagr: 0.072, five_year_cagr: 0.072,
    risk_rating: 1, min_risk_bucket: 'conservative', priority: 4,
    description: '5-year government-backed savings certificate at 7.7% p.a. — interest taxable but qualifies for 80C.',
    why_recommended: 'Safest 80C tax-saving debt option — sovereign guarantee, no market risk, fixed 7.7% return.',
  },
  {
    id: 'db21',
    name: 'SCSS (Senior Citizen Savings Scheme)',
    ticker: 'SCSS',
    asset_class: 'debt', sub_class: 'government-scheme',
    expense_ratio: 0, three_year_cagr: 0.081, five_year_cagr: 0.081,
    risk_rating: 1, min_risk_bucket: 'conservative', priority: 5,
    description: 'Government scheme for 60+ investors — highest guaranteed return at 8.2% p.a., quarterly payout.',
    why_recommended: 'Best post-retirement income scheme — sovereign backing, quarterly income, higher rate than FD.',
  },
  {
    id: 'db22',
    name: 'Sukanya Samriddhi Yojana (SSY)',
    ticker: 'SSY',
    asset_class: 'debt', sub_class: 'government-scheme',
    expense_ratio: 0, three_year_cagr: 0.082, five_year_cagr: 0.082,
    risk_rating: 1, min_risk_bucket: 'conservative', priority: 6,
    description: 'Girl child savings scheme — 8.2% tax-free returns, 80C eligible, matures at daughter\'s age 21.',
    why_recommended: 'Highest tax-free sovereign return available — mandatory for parents of girl children under 10.',
  },
  {
    id: 'db23',
    name: 'Post Office Monthly Income Scheme (POMIS)',
    ticker: 'POMIS',
    asset_class: 'debt', sub_class: 'government-scheme',
    expense_ratio: 0, three_year_cagr: 0.074, five_year_cagr: 0.074,
    risk_rating: 1, min_risk_bucket: 'conservative', priority: 6,
    description: '5-year sovereign scheme paying 7.4% p.a. monthly — max ₹9L single / ₹15L joint account.',
    why_recommended: 'Reliable monthly income with zero default risk — ideal for retirees needing regular cash flow.',
  },
  {
    id: 'db24',
    name: 'RBI Floating Rate Savings Bond 2020',
    ticker: 'RBI-FRB',
    asset_class: 'debt', sub_class: 'government-scheme',
    expense_ratio: 0, three_year_cagr: 0.082, five_year_cagr: 0.080,
    risk_rating: 1, min_risk_bucket: 'conservative', priority: 5,
    description: '7-year RBI bond linked to NSC rate + 0.35% spread — floating coupon resets every 6 months.',
    why_recommended: 'Direct RBI sovereign bond — inflation-linked returns, better than bank FDs, no credit risk.',
  },
  {
    id: 'db25',
    name: 'NPS Tier 1 — Auto Choice (Moderate)',
    ticker: 'NPS-AUTO',
    asset_class: 'debt', sub_class: 'nps',
    expense_ratio: 0.0009, three_year_cagr: 0.118, five_year_cagr: 0.112,
    risk_rating: 2, min_risk_bucket: 'moderate', priority: 4,
    description: 'National Pension System — lifecycle-based allocation shifting from equity to debt as you age.',
    why_recommended: 'Additional ₹50,000 tax deduction under 80CCD(1B) — lowest cost retirement product in India.',
  },

  // ══════════════════════════════════════════════════════════════════
  // GOLD
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'gd01',
    name: 'Nippon India Gold ETF',
    ticker: 'NI-GOLD',
    asset_class: 'gold', sub_class: 'gold-etf',
    expense_ratio: 0.0044, three_year_cagr: 0.132, five_year_cagr: 0.128,
    risk_rating: 2, min_risk_bucket: 'conservative', priority: 1,
    description: 'Physical gold ETF — each unit represents approximately 1 gram of 99.5% pure gold.',
    why_recommended: 'Best SIP-friendly gold option: real-time pricing, demat convenience, no storage risk.',
  },
  {
    id: 'gd05',
    name: 'ICICI Pru Gold ETF',
    ticker: 'IPRU-GOLD',
    asset_class: 'gold', sub_class: 'gold-etf',
    expense_ratio: 0.0040, three_year_cagr: 0.131, five_year_cagr: 0.127,
    risk_rating: 2, min_risk_bucket: 'conservative', priority: 2,
    description: 'Physical gold ETF from ICICI Prudential — one of the highest liquidity gold ETFs on NSE.',
    why_recommended: 'Tightest bid-ask spread among gold ETFs — ideal for frequent buyers and larger investments.',
  },
  {
    id: 'gd03',
    name: 'HDFC Gold ETF',
    ticker: 'HDFC-GOLD',
    asset_class: 'gold', sub_class: 'gold-etf',
    expense_ratio: 0.0042, three_year_cagr: 0.130, five_year_cagr: 0.126,
    risk_rating: 2, min_risk_bucket: 'conservative', priority: 3,
    description: 'Physical gold ETF from HDFC AMC — one of the most liquid gold ETFs on NSE.',
    why_recommended: 'Low-cost gold ETF — ideal for those already using HDFC AMC for equity funds.',
  },
  {
    id: 'gd02',
    name: 'Axis Gold Fund Direct Growth',
    ticker: 'AXIS-GOLD',
    asset_class: 'gold', sub_class: 'gold-fof',
    expense_ratio: 0.0055, three_year_cagr: 0.128, five_year_cagr: 0.124,
    risk_rating: 2, min_risk_bucket: 'conservative', priority: 4,
    description: 'Fund of funds that invests in Axis Gold ETF — accessible without a demat account.',
    why_recommended: 'Invest in gold via SIP without a demat account — ideal for mutual fund-only investors.',
  },
  {
    id: 'gd06',
    name: 'Kotak Gold Fund Direct Growth',
    ticker: 'KOT-GOLD',
    asset_class: 'gold', sub_class: 'gold-fof',
    expense_ratio: 0.0060, three_year_cagr: 0.129, five_year_cagr: 0.125,
    risk_rating: 2, min_risk_bucket: 'conservative', priority: 5,
    description: 'Gold FoF from Kotak — invests in Kotak Gold ETF, monthly SIP without demat needed.',
    why_recommended: 'Convenient gold SIP for Kotak mutual fund investors — same gold exposure at fund house convenience.',
  },
  {
    id: 'gd04',
    name: 'Sovereign Gold Bond (SGB)',
    ticker: 'SGB',
    asset_class: 'gold', sub_class: 'gold-bond',
    expense_ratio: 0, three_year_cagr: 0.141, five_year_cagr: 0.135,
    risk_rating: 2, min_risk_bucket: 'conservative', priority: 4,
    description: 'Government of India bond linked to gold price — pays 2.5% annual interest on top of price gain.',
    why_recommended: 'Best absolute return on gold: 2.5% guaranteed interest + gold price appreciation + tax-free on maturity.',
  },
  {
    id: 'gd07',
    name: 'SBI Silver ETF',
    ticker: 'SBI-SILVR',
    asset_class: 'gold', sub_class: 'silver-etf',
    expense_ratio: 0.0040, three_year_cagr: 0.148, five_year_cagr: null,
    risk_rating: 3, min_risk_bucket: 'growth', priority: 5,
    description: 'Physical silver ETF — tracks domestic silver prices, each unit represents ~1 gram of silver.',
    why_recommended: 'Industrial metal with higher beta than gold — outperforms during manufacturing and green-energy booms.',
  },
  {
    id: 'gd08',
    name: 'ICICI Pru Silver ETF',
    ticker: 'IPRU-SILVR',
    asset_class: 'gold', sub_class: 'silver-etf',
    expense_ratio: 0.0040, three_year_cagr: 0.146, five_year_cagr: null,
    risk_rating: 3, min_risk_bucket: 'growth', priority: 6,
    description: 'Physical silver ETF — exposure to silver prices used in solar panels, EVs, and electronics.',
    why_recommended: 'Diversify precious metals beyond gold — silver is both monetary metal and critical EV/solar input.',
  },

  // ══════════════════════════════════════════════════════════════════
  // ETF (Equity ETFs — distinct from mutual funds)
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'etf01',
    name: 'HDFC Nifty 50 ETF',
    ticker: 'HDFCNIFETF',
    asset_class: 'equity', sub_class: 'broad-market-etf',
    expense_ratio: 0.0005, three_year_cagr: 0.124, five_year_cagr: 0.151,
    risk_rating: 3, min_risk_bucket: 'conservative', priority: 1,
    description: 'Lowest cost Nifty 50 ETF — 0.05% expense ratio, trades on NSE like a stock.',
    why_recommended: 'Cheapest way to own Nifty 50 — better for large lump sums where brokerage is fixed cost.',
  },
  {
    id: 'etf02',
    name: 'Nippon India ETF Nifty Midcap 150',
    ticker: 'NI-MID150E',
    asset_class: 'equity', sub_class: 'mid-cap-etf',
    expense_ratio: 0.0018, three_year_cagr: 0.265, five_year_cagr: 0.268,
    risk_rating: 4, min_risk_bucket: 'growth', priority: 3,
    description: 'ETF tracking Nifty Midcap 150 index — trades in real-time with the lowest mid-cap ETF costs.',
    why_recommended: 'Real-time mid-cap index exposure at ultra-low cost — ideal for active rebalancers and lump-sum investors.',
  },
  {
    id: 'etf03',
    name: 'Mirae Asset NYSE FANG+ ETF',
    ticker: 'MIRAE-FANG',
    asset_class: 'equity', sub_class: 'international-etf',
    expense_ratio: 0.0050, three_year_cagr: 0.198, five_year_cagr: null,
    risk_rating: 5, min_risk_bucket: 'aggressive', priority: 4,
    description: 'Tracks NYSE FANG+ index — Meta, Apple, Amazon, Alphabet, Netflix, Nvidia, Tesla, Microsoft.',
    why_recommended: 'Concentrated bet on the world\'s most dominant technology companies in one ETF.',
  },
  {
    id: 'etf04',
    name: 'Kotak Nifty PSU Bank ETF',
    ticker: 'KOT-PSUBNK',
    asset_class: 'equity', sub_class: 'sectoral-etf',
    expense_ratio: 0.0015, three_year_cagr: 0.282, five_year_cagr: 0.192,
    risk_rating: 4, min_risk_bucket: 'aggressive', priority: 5,
    description: 'Tracks PSU banking index — SBI, PNB, Bank of Baroda, Canara Bank, Union Bank.',
    why_recommended: 'Tactical play on public sector bank re-rating — deeply undervalued vs private banks historically.',
  },

  // ══════════════════════════════════════════════════════════════════
  // ALTERNATIVES — REITs
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'al01',
    name: 'Embassy Office Parks REIT',
    ticker: 'EMBASSY-R',
    asset_class: 'alternatives', sub_class: 'reit',
    expense_ratio: 0.0100, three_year_cagr: 0.068, five_year_cagr: 0.072,
    risk_rating: 3, min_risk_bucket: 'growth', priority: 1,
    description: 'India\'s largest REIT — 45M+ sq ft of Grade-A office space leased to multinational companies.',
    why_recommended: 'Real estate exposure without buying property: quarterly distributions + price appreciation from premium office parks.',
  },
  {
    id: 'al02',
    name: 'Mindspace Business Parks REIT',
    ticker: 'MSPACE-R',
    asset_class: 'alternatives', sub_class: 'reit',
    expense_ratio: 0.0090, three_year_cagr: 0.071, five_year_cagr: 0.080,
    risk_rating: 3, min_risk_bucket: 'growth', priority: 2,
    description: 'Blackstone-backed commercial REIT with 32M sq ft across Mumbai, Hyderabad, Chennai, Pune.',
    why_recommended: 'Stable distributions from blue-chip tech tenants — good diversifier for a growth-oriented portfolio.',
  },
  {
    id: 'al06',
    name: 'Nexus Select Trust REIT',
    ticker: 'NEXUS-R',
    asset_class: 'alternatives', sub_class: 'reit',
    expense_ratio: 0.0110, three_year_cagr: 0.092, five_year_cagr: null,
    risk_rating: 3, min_risk_bucket: 'growth', priority: 3,
    description: 'India\'s first retail REIT — 17 premium shopping malls across 14 cities including Select City Walk.',
    why_recommended: 'Pure retail real estate play — consumption growth and mall footfalls directly drive distributions.',
  },
  {
    id: 'al07',
    name: 'Brookfield India REIT',
    ticker: 'BIRET-R',
    asset_class: 'alternatives', sub_class: 'reit',
    expense_ratio: 0.0095, three_year_cagr: 0.058, five_year_cagr: null,
    risk_rating: 3, min_risk_bucket: 'growth', priority: 4,
    description: 'Brookfield-managed commercial REIT — Grade-A office campuses in Mumbai, Gurugram, Noida, Kolkata.',
    why_recommended: 'Institutional-grade office management — highest sponsor quality among Indian REITs.',
  },

  // ══════════════════════════════════════════════════════════════════
  // ALTERNATIVES — InvITs (Infrastructure Investment Trusts)
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'al05',
    name: 'IndInfravit Trust',
    ticker: 'INDINVIT',
    asset_class: 'alternatives', sub_class: 'infra-invit',
    expense_ratio: 0.0150, three_year_cagr: 0.059, five_year_cagr: null,
    risk_rating: 3, min_risk_bucket: 'growth', priority: 4,
    description: 'Infrastructure investment trust holding toll-road assets — predictable toll revenue from highways.',
    why_recommended: 'Stable, inflation-linked distributions from highway toll revenue — uncorrelated to equity markets.',
  },
  {
    id: 'al08',
    name: 'IRB InvIT Fund',
    ticker: 'IRB-INVIT',
    asset_class: 'alternatives', sub_class: 'infra-invit',
    expense_ratio: 0.0140, three_year_cagr: 0.078, five_year_cagr: 0.074,
    risk_rating: 3, min_risk_bucket: 'growth', priority: 3,
    description: 'Road infrastructure InvIT — 22 operational toll roads across major highway corridors in India.',
    why_recommended: 'Steady quarterly toll revenue with inflation escalation — real asset returns uncorrelated to equity.',
  },
  {
    id: 'al09',
    name: 'PowerGrid InvIT',
    ticker: 'PGRID-INVIT',
    asset_class: 'alternatives', sub_class: 'infra-invit',
    expense_ratio: 0.0120, three_year_cagr: 0.084, five_year_cagr: null,
    risk_rating: 2, min_risk_bucket: 'growth', priority: 2,
    description: 'PowerGrid-sponsored InvIT — transmission line assets with regulated tariffs from central government.',
    why_recommended: 'Government-regulated returns from power grid — near sovereign reliability with regular quarterly income.',
  },

  // ══════════════════════════════════════════════════════════════════
  // ALTERNATIVES — International Funds
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'al04',
    name: 'Mirae Asset S&P 500 Top 50 ETF FoF Direct Growth',
    ticker: 'MIRAE-SP',
    asset_class: 'alternatives', sub_class: 'international-equity',
    expense_ratio: 0.0045, three_year_cagr: 0.162, five_year_cagr: 0.178,
    risk_rating: 4, min_risk_bucket: 'aggressive', priority: 2,
    description: 'FoF tracking the top 50 US megacap stocks — Apple, Microsoft, Nvidia, Amazon, Meta, Alphabet.',
    why_recommended: 'Concentrated US megacap exposure — benefits from USD appreciation and dominant global tech businesses.',
  },
  {
    id: 'al10',
    name: 'PGIM India Emerging Markets Equity Fund Direct Growth',
    ticker: 'PGIM-EM',
    asset_class: 'alternatives', sub_class: 'international-equity',
    expense_ratio: 0.0098, three_year_cagr: 0.092, five_year_cagr: 0.114,
    risk_rating: 4, min_risk_bucket: 'aggressive', priority: 3,
    description: 'Invests in emerging market equities globally — China, Taiwan, South Korea, Brazil alongside India.',
    why_recommended: 'True global EM diversification — reduces India-concentration risk while staying in high-growth economies.',
  },
  {
    id: 'al11',
    name: 'Edelweiss US Technology Equity FoF Direct Growth',
    ticker: 'EDEL-UST',
    asset_class: 'alternatives', sub_class: 'international-equity',
    expense_ratio: 0.0060, three_year_cagr: 0.148, five_year_cagr: 0.192,
    risk_rating: 5, min_risk_bucket: 'aggressive', priority: 4,
    description: 'FoF investing in US technology sector fund — pure play on American tech innovation.',
    why_recommended: 'Deep US tech exposure beyond Nasdaq 100 — includes mid-cap tech companies at early growth stages.',
  },

  // ══════════════════════════════════════════════════════════════════
  // ALTERNATIVES — Commodities & Multi-Asset
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'al03',
    name: 'Nippon India Commodities Fund Direct Growth',
    ticker: 'NI-COMM',
    asset_class: 'alternatives', sub_class: 'commodities',
    expense_ratio: 0.0120, three_year_cagr: 0.084, five_year_cagr: 0.078,
    risk_rating: 3, min_risk_bucket: 'growth', priority: 3,
    description: 'Diversified commodity fund — exposure to energy, metals, and agricultural commodities.',
    why_recommended: 'Inflation hedge beyond gold — commodity prices often rise when equities fall.',
  },
  {
    id: 'al12',
    name: 'ICICI Pru Multi Asset Fund Direct Growth',
    ticker: 'IPRU-MA',
    asset_class: 'alternatives', sub_class: 'multi-asset',
    expense_ratio: 0.0080, three_year_cagr: 0.178, five_year_cagr: 0.162,
    risk_rating: 3, min_risk_bucket: 'moderate', priority: 2,
    description: 'Invests across equity, debt, gold, and REITs — auto-rebalancing across asset classes.',
    why_recommended: 'Single-fund diversification — for investors who want automatic asset allocation without managing multiple funds.',
  },
  {
    id: 'al13',
    name: 'HDFC Balanced Advantage Fund Direct Growth',
    ticker: 'HDFC-BAF',
    asset_class: 'alternatives', sub_class: 'balanced-advantage',
    expense_ratio: 0.0078, three_year_cagr: 0.182, five_year_cagr: 0.168,
    risk_rating: 3, min_risk_bucket: 'moderate', priority: 2,
    description: 'Dynamic equity allocation fund — increases equity when markets fall, reduces when expensive.',
    why_recommended: 'Built-in buy-low sell-high mechanism — removes emotional investing, suitable for 5+ year horizon.',
  },
  {
    id: 'al14',
    name: 'SBI Arbitrage Opportunities Fund Direct Growth',
    ticker: 'SBI-ARB',
    asset_class: 'alternatives', sub_class: 'arbitrage',
    expense_ratio: 0.0040, three_year_cagr: 0.068, five_year_cagr: 0.066,
    risk_rating: 1, min_risk_bucket: 'conservative', priority: 5,
    description: 'Exploits price difference between spot and futures markets — equity taxation with near-debt risk.',
    why_recommended: 'Tax-efficient short-term parking: equity fund taxation (15% STCG) with near-zero market risk.',
  },
]

export const CASH_INSTRUMENT = {
  id: 'cash01',
  name: 'High-Yield Savings / Liquid Fund',
  ticker: 'LIQUID',
  asset_class: 'cash', sub_class: 'savings',
  expense_ratio: 0.0020, three_year_cagr: 0.065, five_year_cagr: 0.060,
  risk_rating: 1, min_risk_bucket: 'conservative', priority: 1,
  description: 'Park short-term cash in a liquid fund (HDFC/ICICI/SBI) or a high-yield digital savings account.',
  why_recommended: 'Capital safety with T+1 liquidity — better than letting cash sit idle in a regular savings account.',
}
